baseURL = 'https://stefanistkuhl.github.io'
languageCode = 'en-us'
title = 'silly blog'
theme = "paper"
# theme = "dead-simple"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "root"
    name       = "root"
    url        = "/"
[params]
  ShowSocialIcons = true
  ShowSocialIconsInFooter = true
  author = "stefi"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/stefanistkuhl"

